name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Si mai fallés per navegador, descomenta aquest bloc:
      # - name: Install Firefox (fallback)
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y firefox-esr

      - name: Run tests (headless)
        run: |
          MOZ_HEADLESS=1 python manage.py test
